import type { SpeakingFeedback } from "@/lib/learning/speaking-grader";
import type { PlanInput } from "@/lib/learning/planner";
import type { DailySession, LearningGoalId, LevelId, SpeakingExercise, VocabularyWord } from "@/types";

/**
 * The AI seam.
 *
 * Nothing in the app calls a model directly. Everything goes through this
 * interface, so the learning experience can be generated by a real provider,
 * by the built-in deterministic engine, or by a mixture of both — and swapping
 * providers is a one-line change in `getAIProvider`.
 */
export interface AIProvider {
  readonly name: string;
  /** True when a real model is answering, false for the offline engine. */
  readonly live: boolean;

  /** Build the structured session for one day. */
  planDailySession(input: PlanInput): Promise<DailySession>;

  /** Evaluate a spoken/written answer to a scenario with coaching feedback. */
  gradeSpeaking(input: {
    answer: string;
    scenario: SpeakingExercise;
    level: LevelId;
  }): Promise<SpeakingFeedback>;

  /** Explain a grammar point in the learner's context. */
  explainGrammar(input: { question: string; level: LevelId; goal: LearningGoalId }): Promise<string>;

  /** Produce an extra example sentence for a word, tuned to the learner's goal. */
  vocabularyExample(input: { word: VocabularyWord; goal: LearningGoalId }): Promise<string>;

  /** Short written feedback on free text the learner produced. */
  writingFeedback(input: { text: string; level: LevelId }): Promise<{
    summary: string;
    suggestions: string[];
  }>;
}
