import type { ListeningExercise } from "@/types";

/**
 * The listening ladder. Every tier steps up on speed, contraction density,
 * idiom load and sentence length — never only on topic.
 *
 * `rate` is the playback rate handed to the speech engine, so "native" tier
 * really does sound faster than "easy".
 */
export const LISTENING: ListeningExercise[] = [
  {
    id: "li-coffee-order",
    title: "Ordering coffee",
    tier: "easy",
    accent: "usa",
    seconds: 40,
    topics: ["travel", "everyday", "restaurant"],
    lines: [
      { speaker: "Barista", text: "Hi there! What can I get you?", rate: 0.92 },
      { speaker: "You", text: "Can I get a medium latte, please?", rate: 0.92 },
      { speaker: "Barista", text: "Sure. For here or to go?", rate: 0.92 },
      { speaker: "You", text: "To go, thanks.", rate: 0.92 },
      { speaker: "Barista", text: "That's four fifty. Anything else?", rate: 0.92 },
      { speaker: "You", text: "No, I'm good, thanks.", rate: 0.92 },
    ],
    questions: [
      {
        id: "li-coffee-q1",
        prompt: "What does the customer order?",
        options: ["A small espresso", "A medium latte", "A large tea", "A cappuccino"],
        answerIndex: 1,
        explanation: "'Can I get a medium latte, please?' — 'Can I get…' is the standard American way to order.",
      },
      {
        id: "li-coffee-q2",
        prompt: "Is the customer eating in the café?",
        options: ["Yes", "No, it's to go", "The barista doesn't ask", "They don't decide"],
        answerIndex: 1,
        explanation: "'For here or to go?' — the answer 'to go' means taking it away (UK: 'takeaway').",
      },
      {
        id: "li-coffee-q3",
        prompt: "What does 'I'm good' mean here?",
        options: ["I feel well", "Yes please", "No thank you", "I'm ready"],
        answerIndex: 2,
        explanation: "After an offer, 'I'm good' is a polite refusal — a very common trap for learners.",
      },
    ],
    hardExpressions: [
      { phrase: "What can I get you?", meaning: "What would you like to order?" },
      { phrase: "For here or to go?", meaning: "Eat in the café, or take it away?" },
      { phrase: "I'm good", meaning: "No thank you (in response to an offer)." },
    ],
  },
  {
    id: "li-first-day",
    title: "First day at a new job",
    tier: "easy",
    accent: "uk",
    seconds: 50,
    topics: ["workplace", "smalltalk", "social"],
    lines: [
      { speaker: "Priya", text: "You must be the new starter. I'm Priya.", rate: 0.95 },
      { speaker: "You", text: "Yes, hi. Nice to meet you.", rate: 0.95 },
      { speaker: "Priya", text: "How are you finding it so far?", rate: 0.95 },
      { speaker: "You", text: "A bit overwhelming, to be honest.", rate: 0.95 },
      { speaker: "Priya", text: "Totally normal. You'll get the hang of it by next week.", rate: 0.95 },
      { speaker: "Priya", text: "Give me a shout if anything's confusing.", rate: 0.95 },
    ],
    questions: [
      {
        id: "li-first-q1",
        prompt: "What does Priya mean by 'How are you finding it?'",
        options: [
          "Where did you find the office?",
          "What is your opinion of it so far?",
          "Did you find your desk?",
          "Are you looking for something?",
        ],
        answerIndex: 1,
        explanation: "'How are you finding it?' asks for your impression of an experience, not for a location.",
      },
      {
        id: "li-first-q2",
        prompt: "'Give me a shout' means…",
        options: ["Speak loudly", "Contact me", "Complain to me", "Shout across the room"],
        answerIndex: 1,
        explanation: "'Give me a shout' = get in touch. Very common in British workplaces.",
      },
    ],
    hardExpressions: [
      { phrase: "the new starter", meaning: "The person who has just joined the company (UK)." },
      { phrase: "get the hang of it", meaning: "Learn how to do it with a bit of practice." },
      { phrase: "give me a shout", meaning: "Contact me / ask me." },
    ],
  },
  {
    id: "li-directions",
    title: "Asking for directions",
    tier: "normal",
    accent: "uk",
    seconds: 45,
    topics: ["travel", "directions", "street"],
    lines: [
      { speaker: "You", text: "Excuse me, do you know where the nearest tube station is?", rate: 1 },
      { speaker: "Local", text: "Yeah, you're not far. Go straight down here, past the chemist,", rate: 1.02 },
      { speaker: "Local", text: "then it's the second left — you can't miss it, there's a big sign.", rate: 1.02 },
      { speaker: "You", text: "Second left after the chemist. Cheers.", rate: 1 },
      { speaker: "Local", text: "No worries. It's about five minutes, tops.", rate: 1.02 },
    ],
    questions: [
      {
        id: "li-dir-q1",
        prompt: "Which turn should you take?",
        options: ["First right", "Second left", "Second right", "First left"],
        answerIndex: 1,
        explanation: "'Then it's the second left' — landmark first (the chemist), then the turn.",
      },
      {
        id: "li-dir-q2",
        prompt: "'You can't miss it' means…",
        options: [
          "You must not be late",
          "It's very easy to find",
          "Don't skip it",
          "It's easy to walk past",
        ],
        answerIndex: 1,
        explanation: "'You can't miss it' reassures you that the place is obvious.",
      },
      {
        id: "li-dir-q3",
        prompt: "How long is the walk?",
        options: ["About 15 minutes", "Half an hour", "Five minutes at most", "It isn't said"],
        answerIndex: 2,
        explanation: "'About five minutes, tops' — 'tops' means 'at maximum'.",
      },
    ],
    hardExpressions: [
      { phrase: "the chemist", meaning: "Pharmacy (British English)." },
      { phrase: "you can't miss it", meaning: "It's impossible not to notice." },
      { phrase: "five minutes, tops", meaning: "Five minutes at the very most." },
    ],
  },
  {
    id: "li-standup",
    title: "A team stand-up meeting",
    tier: "normal",
    accent: "usa",
    seconds: 60,
    topics: ["workplace", "meetings", "business"],
    lines: [
      { speaker: "Dana", text: "Alright, let's kick off. Marco, where are we on the migration?", rate: 1.05 },
      { speaker: "Marco", text: "Mostly there. I hit a snag with the old records, so I'm about a day behind.", rate: 1.05 },
      { speaker: "Dana", text: "Okay. Heads-up, the client demo moved to Thursday.", rate: 1.08 },
      { speaker: "Marco", text: "Thursday's tight, but doable if I drop the reporting piece for now.", rate: 1.05 },
      { speaker: "Dana", text: "Let's park the reporting and circle back after the demo.", rate: 1.08 },
    ],
    questions: [
      {
        id: "li-stand-q1",
        prompt: "What problem does Marco mention?",
        options: [
          "He lost the files",
          "He ran into a problem with old records",
          "He's on holiday",
          "The client cancelled",
        ],
        answerIndex: 1,
        explanation: "'I hit a snag' = I ran into an unexpected problem.",
      },
      {
        id: "li-stand-q2",
        prompt: "What is decided about the reporting work?",
        options: [
          "It's cancelled permanently",
          "It's postponed until after the demo",
          "Dana will do it",
          "It's the top priority",
        ],
        answerIndex: 1,
        explanation: "'Let's park the reporting and circle back after the demo' — postponed, not dropped.",
      },
      {
        id: "li-stand-q3",
        prompt: "'Thursday's tight, but doable' means…",
        options: [
          "Thursday is impossible",
          "Thursday is difficult but possible",
          "Thursday is easy",
          "Thursday is already booked",
        ],
        answerIndex: 1,
        explanation: "'Tight' = little margin; 'doable' = it can be done.",
      },
    ],
    hardExpressions: [
      { phrase: "hit a snag", meaning: "Run into an unexpected problem." },
      { phrase: "park it", meaning: "Postpone a topic deliberately." },
      { phrase: "tight but doable", meaning: "Difficult because of time, but possible." },
    ],
  },
  {
    id: "li-flat-viewing",
    title: "Viewing an apartment",
    tier: "normal",
    accent: "ireland",
    seconds: 55,
    topics: ["housing", "admin", "everyday"],
    lines: [
      { speaker: "Agent", text: "So this is the place. It's grand and bright, south-facing.", rate: 1 },
      { speaker: "You", text: "Are the bills included in the rent?", rate: 1 },
      { speaker: "Agent", text: "Electricity isn't, but heating and bins are. Deposit's one month up front.", rate: 1.05 },
      { speaker: "You", text: "And how soon could I move in?", rate: 1 },
      { speaker: "Agent", text: "Once the references come back, you're looking at about two weeks.", rate: 1.05 },
    ],
    questions: [
      {
        id: "li-flat-q1",
        prompt: "Which bill is NOT included?",
        options: ["Heating", "Bins", "Electricity", "Water"],
        answerIndex: 2,
        explanation: "'Electricity isn't, but heating and bins are.'",
      },
      {
        id: "li-flat-q2",
        prompt: "What has to happen before moving in?",
        options: [
          "A second viewing",
          "References must come back",
          "A year's rent must be paid",
          "The flat must be painted",
        ],
        answerIndex: 1,
        explanation: "'Once the references come back' — a condition before the move.",
      },
    ],
    hardExpressions: [
      { phrase: "grand", meaning: "Fine / nice (Irish usage)." },
      { phrase: "one month up front", meaning: "One month's rent paid in advance." },
      { phrase: "you're looking at about two weeks", meaning: "Expect roughly two weeks." },
    ],
  },
  {
    id: "li-interview",
    title: "A job interview answer",
    tier: "challenging",
    accent: "usa",
    seconds: 70,
    topics: ["workplace", "business", "interview", "opinion"],
    lines: [
      { speaker: "Interviewer", text: "Tell me about a time a project didn't go to plan.", rate: 1.08 },
      {
        speaker: "Candidate",
        text: "Sure. Last year we rolled out a new booking system, and honestly, the first week was rough.",
        rate: 1.12,
      },
      {
        speaker: "Candidate",
        text: "We'd underestimated how much training the staff needed, so support tickets went through the roof.",
        rate: 1.12,
      },
      {
        speaker: "Candidate",
        text: "I pulled together a quick session, wrote a one-page cheat sheet, and within two weeks tickets were back to normal.",
        rate: 1.12,
      },
      {
        speaker: "Interviewer",
        text: "And what would you do differently now?",
        rate: 1.08,
      },
      {
        speaker: "Candidate",
        text: "Train first, launch second. That's the main takeaway I carried into the next rollout.",
        rate: 1.12,
      },
    ],
    questions: [
      {
        id: "li-int-q1",
        prompt: "What went wrong with the rollout?",
        options: [
          "The system crashed",
          "Staff weren't trained enough",
          "The budget was cut",
          "The client cancelled",
        ],
        answerIndex: 1,
        explanation: "'We'd underestimated how much training the staff needed.'",
      },
      {
        id: "li-int-q2",
        prompt: "'Tickets went through the roof' means…",
        options: [
          "Tickets were lost",
          "Tickets increased dramatically",
          "Tickets were resolved",
          "Tickets were sent upstairs",
        ],
        answerIndex: 1,
        explanation: "'Go through the roof' = rise very sharply.",
      },
      {
        id: "li-int-q3",
        prompt: "What is the candidate's lesson?",
        options: [
          "Launch quickly and fix later",
          "Hire more support staff",
          "Train before launching",
          "Avoid new systems",
        ],
        answerIndex: 2,
        explanation: "'Train first, launch second' — stated as the main takeaway.",
      },
    ],
    hardExpressions: [
      { phrase: "didn't go to plan", meaning: "Didn't happen the way it was planned." },
      { phrase: "went through the roof", meaning: "Increased very sharply." },
      { phrase: "pulled together", meaning: "Organised quickly." },
      { phrase: "the main takeaway", meaning: "The key lesson to remember." },
    ],
  },
  {
    id: "li-doctor",
    title: "At the doctor's surgery",
    tier: "challenging",
    accent: "uk",
    seconds: 65,
    topics: ["health", "admin", "everyday"],
    lines: [
      { speaker: "GP", text: "Right, so what's brought you in today?", rate: 1.08 },
      { speaker: "You", text: "I've had a cough that just won't shift for about three weeks.", rate: 1.05 },
      { speaker: "GP", text: "Any temperature, shortness of breath, anything like that?", rate: 1.12 },
      { speaker: "You", text: "No fever. It's worse at night, though.", rate: 1.05 },
      {
        speaker: "GP",
        text: "Let's have a listen to your chest. If it's still hanging around in a fortnight, we'll do a chest X-ray.",
        rate: 1.12,
      },
    ],
    questions: [
      {
        id: "li-doc-q1",
        prompt: "'A cough that won't shift' means…",
        options: [
          "A cough that moves around",
          "A cough that won't go away",
          "A cough that changes at night",
          "A cough caused by work",
        ],
        answerIndex: 1,
        explanation: "'Shift' here means 'go away' — very common British usage for illness.",
      },
      {
        id: "li-doc-q2",
        prompt: "When would an X-ray be arranged?",
        options: [
          "Today",
          "If it continues for another two weeks",
          "Only if a fever appears",
          "Never",
        ],
        answerIndex: 1,
        explanation: "'In a fortnight' = in two weeks (British English).",
      },
    ],
    hardExpressions: [
      { phrase: "what's brought you in today?", meaning: "Why have you come to see me?" },
      { phrase: "won't shift", meaning: "Won't go away (UK)." },
      { phrase: "hanging around", meaning: "Still present, persisting." },
      { phrase: "a fortnight", meaning: "Two weeks (UK/Ireland)." },
    ],
  },
  {
    id: "li-friends-plans",
    title: "Friends making plans (fast, casual)",
    tier: "native",
    accent: "usa",
    seconds: 55,
    topics: ["social", "friends", "street", "slang"],
    lines: [
      { speaker: "Sam", text: "Yo, we still on for Saturday or nah?", rate: 1.22 },
      { speaker: "You", text: "Yeah, I'm down. What time were you thinking?", rate: 1.18 },
      {
        speaker: "Sam",
        text: "I dunno, like sevenish? Jess is gonna be late 'cause she's got that thing with her sister.",
        rate: 1.25,
      },
      { speaker: "You", text: "Sevenish works. Should we just meet there?", rate: 1.18 },
      { speaker: "Sam", text: "Yeah, let's just meet there. I'll hit you up when I'm leaving.", rate: 1.25 },
    ],
    questions: [
      {
        id: "li-fr-q1",
        prompt: "What time are they meeting?",
        options: ["Six", "Around seven", "Seven thirty exactly", "Eight"],
        answerIndex: 1,
        explanation: "'Sevenish' = around seven. The '-ish' suffix makes any time approximate.",
      },
      {
        id: "li-fr-q2",
        prompt: "Why will Jess be late?",
        options: [
          "She's working",
          "She has something with her sister",
          "She's travelling",
          "It isn't explained",
        ],
        answerIndex: 1,
        explanation: "'she's got that thing with her sister' — 'that thing' is a vague, very natural placeholder.",
      },
      {
        id: "li-fr-q3",
        prompt: "'I'll hit you up' means…",
        options: ["I'll pick you up", "I'll message you", "I'll pay you", "I'll wake you up"],
        answerIndex: 1,
        explanation: "'Hit you up' = contact you, usually by text.",
      },
    ],
    hardExpressions: [
      { phrase: "we still on?", meaning: "Is the plan still happening?" },
      { phrase: "or nah", meaning: "Or not? (very casual)" },
      { phrase: "sevenish", meaning: "Around seven o'clock." },
      { phrase: "hit you up", meaning: "Message you." },
    ],
  },
  {
    id: "li-podcast",
    title: "Podcast clip: why habits beat motivation",
    tier: "native",
    accent: "canada",
    seconds: 75,
    topics: ["media", "academic", "opinion", "lecture"],
    lines: [
      {
        speaker: "Host",
        text: "So the thing people get wrong about motivation is they treat it like fuel — like you need a full tank before you start.",
        rate: 1.2,
      },
      {
        speaker: "Guest",
        text: "Right, and it's actually the opposite. Action comes first, and motivation kind of shows up afterwards, once you're already moving.",
        rate: 1.25,
      },
      {
        speaker: "Host",
        text: "Which is why the ten-minute rule works so well — you're not committing to an hour, you're just lowering the barrier to entry.",
        rate: 1.25,
      },
      {
        speaker: "Guest",
        text: "Exactly. And once you're ten minutes in, more often than not you'll keep going anyway.",
        rate: 1.25,
      },
    ],
    questions: [
      {
        id: "li-pod-q1",
        prompt: "What is the speakers' main claim?",
        options: [
          "Motivation must come before action",
          "Action tends to create motivation",
          "Motivation is a myth",
          "Habits require an hour a day",
        ],
        answerIndex: 1,
        explanation: "'Action comes first, and motivation… shows up afterwards.'",
      },
      {
        id: "li-pod-q2",
        prompt: "Why does the ten-minute rule work, according to the host?",
        options: [
          "Ten minutes is enough practice",
          "It lowers the barrier to starting",
          "It builds a full tank of motivation",
          "It replaces habits",
        ],
        answerIndex: 1,
        explanation: "'You're just lowering the barrier to entry.'",
      },
      {
        id: "li-pod-q3",
        prompt: "'More often than not' means…",
        options: ["Rarely", "Never", "Usually", "Exactly half the time"],
        answerIndex: 2,
        explanation: "'More often than not' = in most cases.",
      },
    ],
    hardExpressions: [
      { phrase: "treat it like fuel", meaning: "Think of it as something you need a supply of first." },
      { phrase: "barrier to entry", meaning: "How hard it is to start something." },
      { phrase: "more often than not", meaning: "Usually." },
    ],
  },
  {
    id: "li-customer-complaint",
    title: "Handling an unhappy customer",
    tier: "challenging",
    accent: "australia",
    seconds: 60,
    topics: ["clients", "business", "problems", "phone"],
    lines: [
      { speaker: "Customer", text: "Look, this is the third time I've called about the same issue.", rate: 1.1 },
      { speaker: "You", text: "I'm sorry — that's genuinely frustrating. Let me look into it right now.", rate: 1.08 },
      { speaker: "Customer", text: "I've been told that before and nothing's happened, mate.", rate: 1.15 },
      {
        speaker: "You",
        text: "Fair enough. Here's what I'll do differently: I'll stay on the line while I fix it, and I'll email you confirmation before we hang up.",
        rate: 1.1,
      },
      { speaker: "Customer", text: "Yeah, alright. That's better.", rate: 1.12 },
    ],
    questions: [
      {
        id: "li-cust-q1",
        prompt: "What does the agent promise?",
        options: [
          "A refund",
          "To fix it while staying on the call and email confirmation",
          "To call back tomorrow",
          "To escalate to a manager",
        ],
        answerIndex: 1,
        explanation: "'I'll stay on the line while I fix it, and I'll email you confirmation.'",
      },
      {
        id: "li-cust-q2",
        prompt: "What does 'fair enough' signal here?",
        options: [
          "The agent disagrees",
          "The agent accepts the customer's frustration as reasonable",
          "The agent is ending the call",
          "The agent is confused",
        ],
        answerIndex: 1,
        explanation: "'Fair enough' accepts the other person's point without argument — de-escalating.",
      },
    ],
    hardExpressions: [
      { phrase: "fair enough", meaning: "I accept that your point is reasonable." },
      { phrase: "stay on the line", meaning: "Not hang up the phone." },
      { phrase: "mate", meaning: "Friendly address term (AU/UK) — can be pointed when someone is annoyed." },
    ],
  },
];

export const LISTENING_BY_ID = new Map(LISTENING.map((l) => [l.id, l]));
