import type { RealEnglishCategoryId, RealEnglishPhrase } from "@/types";

export const REAL_ENGLISH_CATEGORY_META: Record<
  RealEnglishCategoryId,
  { label: string; blurb: string; icon: string }
> = {
  street: {
    label: "Street English",
    blurb: "What people actually say on the pavement, in shops, in queues.",
    icon: "🛹",
  },
  workplace: {
    label: "Workplace English",
    blurb: "Meetings, Slack, corridors — polite, efficient, slightly indirect.",
    icon: "💼",
  },
  american: {
    label: "American English",
    blurb: "Expressions and reductions you'll hear constantly in the US.",
    icon: "🇺🇸",
  },
  british: {
    label: "British English",
    blurb: "Understatement, softeners, and words the US doesn't use.",
    icon: "🇬🇧",
  },
  travel: {
    label: "Travel English",
    blurb: "Airports, hotels, taxis, and the moment something goes wrong.",
    icon: "✈️",
  },
  social: {
    label: "Social English",
    blurb: "Reacting, agreeing, escaping conversations gracefully.",
    icon: "🫱",
  },
  internet: {
    label: "Internet English",
    blurb: "Comments, group chats, memes — written but spoken-sounding.",
    icon: "💬",
  },
  business: {
    label: "Business English",
    blurb: "Negotiation, diplomacy, and saying no without saying no.",
    icon: "📈",
  },
};

export const REAL_ENGLISH: RealEnglishPhrase[] = [
  {
    id: "re-head-out",
    category: "street",
    phrase: "I'm gonna head out.",
    meaning: "I'm going to leave (now or soon).",
    darija: "غادي نمشي / نخرج دابا.",
    naturalExample: "It's getting late — I'm gonna head out. See you tomorrow.",
    whenToUse: "Leaving a party, an office, or a friend's place. It announces your exit softly, without the drama of 'goodbye'.",
    formalAlternative: "I'm afraid I'll have to be going.",
    informalAlternative: "I'm off. / I'm gonna take off.",
    register: "casual",
    note: "Native speakers rarely say 'I will leave now'. 'Head out' frames leaving as a direction, not an announcement, so it sounds relaxed. 'Gonna' is the natural spoken form of 'going to' — write 'going to', say 'gonna'.",
    regions: ["usa", "canada", "uk", "australia", "ireland"],
    level: "elementary",
  },
  {
    id: "re-whats-up",
    category: "street",
    phrase: "What's up?",
    meaning: "Hello / how are you? — usually not a real question.",
    darija: "أهلا / كيف داير؟ — عادة ماشي سؤال بصح، غير تحية.",
    naturalExample: "— Hey, what's up? — Not much, you?",
    whenToUse: "Greeting friends and peers. The expected answer is short: 'Not much' or 'Not a lot, you?'",
    formalAlternative: "How are you today?",
    informalAlternative: "What's good? / Sup?",
    register: "casual",
    note: "Answering with a detailed report of your life sounds odd. It's a greeting shaped like a question — treat it like 'hello'.",
    regions: ["usa", "canada"],
    level: "beginner",
  },
  {
    id: "re-my-bad",
    category: "street",
    phrase: "My bad.",
    meaning: "My mistake, sorry.",
    darija: "غلطتي، سمح ليا. غير فالحوايج الصغيرة.",
    naturalExample: "Oh, that was my bad — I sent the wrong file.",
    whenToUse: "Small, low-stakes mistakes with people you know. Never for a serious apology.",
    formalAlternative: "I apologise, that was my error.",
    informalAlternative: "Sorry, that's on me.",
    register: "slang",
    note: "Using 'my bad' after something serious sounds careless. Scale your apology to the damage.",
    regions: ["usa", "canada"],
    level: "elementary",
  },
  {
    id: "re-im-good",
    category: "street",
    phrase: "I'm good.",
    meaning: "No thanks / I don't need anything — or, I'm fine.",
    darija: "لا شكرا / أنا مزيان — حسب السياق.",
    naturalExample: "— Want another coffee? — I'm good, thanks.",
    whenToUse: "Politely declining an offer of food, drink or help.",
    formalAlternative: "No, thank you, I'm fine.",
    informalAlternative: "I'm all set. (US)",
    register: "casual",
    note: "Learners often hear 'I'm good' as 'yes, I'm well'. In an offer context it means no. Context decides.",
    regions: ["usa", "canada", "uk"],
    level: "elementary",
  },
  {
    id: "re-hang-on-sec",
    category: "street",
    phrase: "Hang on a sec.",
    meaning: "Wait a moment.",
    darija: "تسنى شوية.",
    naturalExample: "Hang on a sec, I'll grab my jacket.",
    whenToUse: "Any short pause: on the phone, at a door, mid-conversation.",
    formalAlternative: "Would you mind waiting a moment?",
    informalAlternative: "Gimme a sec. / Two secs.",
    register: "casual",
    note: "'Sec' is second; 'gimme' is give me. These reductions are normal speech, not sloppy speech.",
    regions: ["uk", "usa", "canada", "australia", "ireland"],
    level: "beginner",
  },
  {
    id: "re-quick-word",
    category: "workplace",
    phrase: "Have you got a minute?",
    meaning: "Can we talk briefly, now?",
    darija: "واش عندك دقيقة نهضر معاك؟",
    naturalExample: "Hey — have you got a minute? It's about the invoice.",
    whenToUse: "Interrupting a colleague politely. Adding the topic immediately is what makes it considerate.",
    formalAlternative: "Would you have a moment to discuss something?",
    informalAlternative: "Got a sec?",
    register: "neutral",
    note: "In English-speaking workplaces you signal the size of the interruption before you make it — 'a minute', 'a sec', 'five minutes'.",
    regions: ["uk", "usa", "canada", "ireland", "australia"],
    level: "elementary",
  },
  {
    id: "re-loop-in",
    category: "workplace",
    phrase: "I'll loop you in.",
    meaning: "I'll include you in the conversation / email thread.",
    darija: "غادي ندخلك معانا فالموضوع / نزيدك فالإيميل.",
    naturalExample: "I'll loop you in on the thread so you see the client's reply.",
    whenToUse: "Email and chat at work, when adding someone to an ongoing discussion.",
    formalAlternative: "I will include you in the correspondence.",
    informalAlternative: "I'll add you in. / I'll cc you.",
    register: "neutral",
    note: "'Keep me in the loop' is the same metaphor from the other side: keep me informed.",
    regions: ["usa", "uk", "canada"],
    level: "intermediate",
  },
  {
    id: "re-not-quite",
    category: "workplace",
    phrase: "That's not quite what I meant.",
    meaning: "You misunderstood me — said gently.",
    darija: "ماشي هادشي اللي قصدت — بطريقة لطيفة.",
    naturalExample: "That's not quite what I meant — I was talking about the second option.",
    whenToUse: "Correcting a misunderstanding without embarrassing anyone.",
    formalAlternative: "Perhaps I didn't express myself clearly.",
    informalAlternative: "Nah, I meant something else.",
    register: "neutral",
    note: "'Not quite' is a softener. Direct correction ('No, you're wrong') is jarring in most English-speaking work cultures; the softener buys goodwill.",
    regions: ["uk", "usa", "canada", "ireland"],
    level: "intermediate",
  },
  {
    id: "re-park-that",
    category: "workplace",
    phrase: "Let's park that for now.",
    meaning: "Let's stop discussing this topic and return to it later.",
    darija: "نحيدو هاد الموضوع دابا ونرجعو ليه من بعد.",
    naturalExample: "Good question — let's park that and come back to it after the demo.",
    whenToUse: "Chairing a meeting that is drifting. It closes a topic without dismissing it.",
    formalAlternative: "May I suggest we defer that point?",
    informalAlternative: "Let's come back to that.",
    register: "neutral",
    note: "Meeting English is full of these polite topic-management phrases. Knowing three of them makes you sound like you belong in the room.",
    regions: ["uk", "usa", "canada", "australia"],
    level: "upper-intermediate",
  },
  {
    id: "re-eod",
    category: "workplace",
    phrase: "by EOD / by COB",
    meaning: "By the end of the (business) day.",
    darija: "قبل ما يسالي نهار الخدمة.",
    naturalExample: "Can you send it over by EOD?",
    whenToUse: "Written work English — email, chat, tickets.",
    formalAlternative: "by the close of business today",
    informalAlternative: "by tonight",
    register: "neutral",
    note: "COB (close of business) is more common in the UK; EOD in the US tech world. If a deadline matters, name the hour — 'by 5pm your time' removes all doubt.",
    regions: ["usa", "uk"],
    level: "intermediate",
  },
  {
    id: "re-gonna-wanna",
    category: "american",
    phrase: "gonna / wanna / gotta",
    meaning: "going to / want to / (have) got to.",
    darija: "غادي / بغيت / خاصني — هكذا كايتنطقو بصح فالهضرة.",
    naturalExample: "I gotta run — I wanna catch the 6:10.",
    whenToUse: "Speaking, always. Writing: only in messages between friends.",
    formalAlternative: "I have to leave — I want to catch the 6:10.",
    informalAlternative: "(same, spoken)",
    register: "casual",
    note: "These are not lazy errors: they are how the language is actually pronounced. Learning to *hear* them is what unlocks fast American speech.",
    regions: ["usa", "canada"],
    level: "elementary",
  },
  {
    id: "re-you-guys",
    category: "american",
    phrase: "you guys",
    meaning: "You (plural) — regardless of gender.",
    darija: "نتوما (للجماعة)، بلا فرق بين ذكور وإناث.",
    naturalExample: "Are you guys coming to lunch?",
    whenToUse: "Casual and semi-professional American English addressing a group.",
    formalAlternative: "everyone / all of you",
    informalAlternative: "y'all (South), folks",
    register: "casual",
    note: "Some workplaces now prefer 'folks', 'everyone' or 'team' as a neutral choice. In formal writing, use 'everyone'.",
    regions: ["usa", "canada"],
    level: "beginner",
  },
  {
    id: "re-for-here",
    category: "american",
    phrase: "For here or to go?",
    meaning: "Will you eat here or take the food away?",
    darija: "غادي تاكل هنا ولا تديها معاك؟",
    naturalExample: "— Large latte, please. — For here or to go?",
    whenToUse: "US cafés and fast food. In the UK you'll hear 'Eat in or takeaway?'",
    formalAlternative: "Will you be dining in?",
    informalAlternative: "To go, please. / Takeaway, please. (UK)",
    register: "neutral",
    note: "This question comes fast and flat: 'ferhere-ertago?'. Recognising the melody matters more than the words.",
    regions: ["usa", "canada"],
    level: "beginner",
  },
  {
    id: "re-are-you-alright",
    category: "british",
    phrase: "You alright?",
    meaning: "Hello / how are you? — a greeting, not concern.",
    darija: "لاباس؟ — تحية بريطانية، ماشي سؤال على صحتك.",
    naturalExample: "— You alright? — Yeah, you?",
    whenToUse: "Everyday British greeting between friends, colleagues, shopkeepers.",
    formalAlternative: "How do you do? (very formal, rare)",
    informalAlternative: "Alright? / Y'alright mate?",
    register: "casual",
    note: "Learners often answer with a health update. The expected reply is a mirror: 'Yeah, you?' — nothing more.",
    regions: ["uk", "ireland"],
    level: "beginner",
  },
  {
    id: "re-not-bad-at-all",
    category: "british",
    phrase: "Not bad at all.",
    meaning: "Actually very good.",
    darija: "مزيانة بزاف — البريطانيين كايقللو من الشي بقصد.",
    naturalExample: "— How was the presentation? — Not bad at all, really.",
    whenToUse: "British understatement: praise delivered as the absence of criticism.",
    formalAlternative: "It was very well received.",
    informalAlternative: "Yeah, it was great.",
    register: "casual",
    note: "British feedback runs about one notch below the intended meaning. 'Not bad' = good. 'Quite good' = fine. 'Interesting' can mean 'I disagree'.",
    regions: ["uk", "ireland"],
    level: "upper-intermediate",
  },
  {
    id: "re-i-might-suggest",
    category: "british",
    phrase: "I wonder if we might…",
    meaning: "I want us to do this — phrased as a wondering.",
    darija: "بغيت هادشي — ولكن بطريقة غير مباشرة وكتبان طلب.",
    naturalExample: "I wonder if we might revisit the deadline?",
    whenToUse: "Formal British requests, especially upwards or with clients.",
    formalAlternative: "Would it be possible to revisit the deadline?",
    informalAlternative: "Can we push the deadline?",
    register: "formal",
    note: "The more indirect the phrasing, the more polite it sounds. This is why British emails can seem to say nothing while making a firm request.",
    regions: ["uk", "ireland"],
    level: "advanced",
  },
  {
    id: "re-cheers",
    category: "british",
    phrase: "Cheers.",
    meaning: "Thanks — or goodbye — or a toast.",
    darija: "شكرا / بسلامة — حسب السياق. بريطانية وأسترالية.",
    naturalExample: "Cheers, mate. See you Monday.",
    whenToUse: "Casual British and Irish English, constantly.",
    formalAlternative: "Thank you.",
    informalAlternative: "Ta. (very informal, UK)",
    register: "casual",
    note: "Ending a work email with 'Cheers,' is normal in the UK and Australia, and slightly odd in the US.",
    regions: ["uk", "ireland", "australia"],
    level: "elementary",
  },
  {
    id: "re-just-looking",
    category: "travel",
    phrase: "I'm just looking, thanks.",
    meaning: "I don't need help — I'm browsing.",
    darija: "غير كنشوف، شكرا.",
    naturalExample: "— Can I help you find anything? — I'm just looking, thanks.",
    whenToUse: "Shops anywhere in the English-speaking world.",
    formalAlternative: "Thank you, I'm simply browsing for now.",
    informalAlternative: "Just having a look, cheers.",
    register: "neutral",
    note: "'Thanks' at the end is what makes it polite instead of dismissive. Dropping it changes the tone completely.",
    regions: ["uk", "usa", "canada", "australia", "ireland"],
    level: "beginner",
  },
  {
    id: "re-could-you-repeat",
    category: "travel",
    phrase: "Sorry, could you say that again?",
    meaning: "I didn't understand — please repeat.",
    darija: "عاود عافاك، ما فهمتش. أهم جملة للمسافر.",
    naturalExample: "Sorry, could you say that again? A bit slower, if you don't mind.",
    whenToUse: "Any time you miss something. This is the single most useful sentence for a traveller.",
    formalAlternative: "I beg your pardon, would you mind repeating that?",
    informalAlternative: "Sorry, what was that?",
    register: "neutral",
    note: "Asking for repetition is normal and expected. Pretending to understand is what creates real problems later.",
    regions: ["uk", "usa", "canada", "australia", "ireland"],
    level: "beginner",
  },
  {
    id: "re-is-this-seat-taken",
    category: "travel",
    phrase: "Is this seat taken?",
    meaning: "May I sit here?",
    darija: "واش هاد البلاصة خاوية؟",
    naturalExample: "Excuse me, is this seat taken?",
    whenToUse: "Trains, cafés, waiting rooms.",
    formalAlternative: "Excuse me, is anyone sitting here?",
    informalAlternative: "Mind if I sit here?",
    register: "neutral",
    note: "The answer is often just a headshake plus 'Go ahead' or 'All yours'. Both mean yes, sit down.",
    regions: ["uk", "usa", "canada", "australia", "ireland"],
    level: "beginner",
  },
  {
    id: "re-flight-delayed",
    category: "travel",
    phrase: "What are my options?",
    meaning: "Tell me what can be done about this problem.",
    darija: "شنو الحلول اللي عندي؟ — كتحول الهضرة من الشكاية للحل.",
    naturalExample: "My connection is cancelled — what are my options?",
    whenToUse: "Airline desks, hotels, customer service. It's assertive without being aggressive.",
    formalAlternative: "Could you outline the alternatives available to me?",
    informalAlternative: "So what can we do here?",
    register: "neutral",
    note: "Complaining describes the problem; this question moves the conversation to solutions, which is what staff can actually act on.",
    regions: ["usa", "uk", "canada", "australia", "ireland"],
    level: "intermediate",
  },
  {
    id: "re-whereabouts-travel",
    category: "travel",
    phrase: "Whereabouts are you staying?",
    meaning: "In which part of the city are you staying?",
    darija: "فين نازل بالضبط؟ — بطريقة ودية.",
    naturalExample: "— We're in Dublin for a week. — Nice, whereabouts?",
    whenToUse: "Friendly small talk with taxi drivers, hosts, new acquaintances.",
    formalAlternative: "In which area are you staying?",
    informalAlternative: "Where you staying?",
    register: "casual",
    note: "'Whereabouts' softens a direct 'where' — it invites a rough answer rather than an address.",
    regions: ["uk", "ireland", "australia"],
    level: "intermediate",
  },
  {
    id: "re-how-come",
    category: "social",
    phrase: "How come?",
    meaning: "Why? — softer and more curious than 'why'.",
    darija: "علاش؟ — بطريقة ألطف وأقل مواجهة.",
    naturalExample: "— I'm not going tonight. — Oh, how come?",
    whenToUse: "Casual conversation. Note the word order: 'How come you didn't go?' — not 'How come didn't you go?'",
    formalAlternative: "May I ask why?",
    informalAlternative: "Why's that?",
    register: "casual",
    note: "'Why?' alone can sound blunt or challenging. 'How come?' signals interest instead of interrogation.",
    regions: ["usa", "canada", "uk", "ireland"],
    level: "elementary",
  },
  {
    id: "re-no-way",
    category: "social",
    phrase: "No way!",
    meaning: "I can't believe it! (surprise) — or, absolutely not.",
    darija: "ما يمكنش! (استغراب) — ولا: مستحيل، لا.",
    naturalExample: "— She got the job. — No way! That's amazing.",
    whenToUse: "Reacting to surprising news among friends.",
    formalAlternative: "That's remarkable.",
    informalAlternative: "You're kidding! / Shut up! (US, playful)",
    register: "casual",
    note: "Reacting is a skill. English conversation expects audible reactions — 'Really?', 'No way!', 'That's rough' — silence reads as disinterest.",
    regions: ["usa", "canada", "uk", "australia", "ireland"],
    level: "beginner",
  },
  {
    id: "re-thats-rough",
    category: "social",
    phrase: "That's rough.",
    meaning: "That sounds difficult — I sympathise.",
    darija: "صعيبة عليك، حاسس بيك.",
    naturalExample: "— I've been sick all week. — Oh, that's rough.",
    whenToUse: "Responding to someone's bad news, casually.",
    formalAlternative: "I'm sorry to hear that.",
    informalAlternative: "That sucks. (very casual)",
    register: "casual",
    note: "'That sucks' is common but too informal for work. 'That's rough' works almost everywhere.",
    regions: ["usa", "canada", "uk", "australia"],
    level: "elementary",
  },
  {
    id: "re-anyway-i-should",
    category: "social",
    phrase: "Anyway, I should let you go.",
    meaning: "I want to end this conversation — politely framed as consideration for you.",
    darija: "بغيت نسالي الهضرة — بطريقة مؤدبة كأنك كتراعي وقتو.",
    naturalExample: "Anyway, I should let you go — say hi to your family.",
    whenToUse: "Ending phone calls and long chats without seeming rude.",
    formalAlternative: "I won't take up any more of your time.",
    informalAlternative: "Right, I'll leave you to it.",
    register: "neutral",
    note: "English conversations close in stages: a signal ('anyway…'), a reason, then goodbye. Hanging up straight after the last topic feels abrupt.",
    regions: ["usa", "uk", "canada", "ireland", "australia"],
    level: "upper-intermediate",
  },
  {
    id: "re-lets-catch-up-soon",
    category: "social",
    phrase: "We should catch up soon.",
    meaning: "It would be nice to meet — sometimes a real plan, often just warmth.",
    darija: "خاصنا نتلاقاو قريبا — بزاف مرات غير كلام لطيف بلا موعد.",
    naturalExample: "Great seeing you! We should catch up soon.",
    whenToUse: "Ending a chance encounter.",
    formalAlternative: "It would be good to meet properly sometime.",
    informalAlternative: "Let's get a coffee sometime.",
    register: "casual",
    note: "If you want a real meeting, follow it with a concrete step: 'Are you free next week?' Otherwise it stays a friendly nothing.",
    regions: ["uk", "usa", "australia", "canada", "ireland"],
    level: "intermediate",
  },
  {
    id: "re-imo",
    category: "internet",
    phrase: "IMO / IMHO",
    meaning: "In my opinion / in my humble opinion.",
    darija: "فرأيي.",
    naturalExample: "IMO the first version was better.",
    whenToUse: "Comments, forums, group chats. Not in professional email.",
    formalAlternative: "In my view,",
    informalAlternative: "tbh I think…",
    register: "casual",
    note: "Written internet English imitates speech. Acronyms carry the tone that intonation would carry out loud.",
    regions: ["usa", "uk", "canada", "australia", "ireland"],
    level: "intermediate",
  },
  {
    id: "re-tbh",
    category: "internet",
    phrase: "tbh / ngl",
    meaning: "To be honest / not gonna lie — both introduce a mild confession.",
    darija: "بصراحة / ما غاديش نكذب عليك.",
    naturalExample: "ngl, I forgot about the deadline completely.",
    whenToUse: "Messages between friends. Never in an email to a manager.",
    formalAlternative: "To be candid,",
    informalAlternative: "honestly…",
    register: "slang",
    note: "These soften an admission and make it sound self-aware rather than careless — the online equivalent of a shrug.",
    regions: ["usa", "uk", "canada", "australia", "ireland"],
    level: "upper-intermediate",
  },
  {
    id: "re-it-hits-different",
    category: "internet",
    phrase: "It hits different.",
    meaning: "It affects you in a special, stronger way.",
    darija: "كتأثر فيك بطريقة خاصة، أقوى من العادة.",
    naturalExample: "That song at 2am hits different.",
    whenToUse: "Social media, casual chat among younger speakers.",
    formalAlternative: "It has a particular impact.",
    informalAlternative: "It's just better somehow.",
    register: "slang",
    note: "Deliberately ungrammatical ('different' where 'differently' belongs) — the grammar break *is* the style. Don't transfer it to formal writing.",
    regions: ["usa", "canada"],
    level: "advanced",
  },
  {
    id: "re-touch-grass",
    category: "internet",
    phrase: "Touch grass.",
    meaning: "Go outside — you've been online too long. A tease, sometimes an insult.",
    darija: "خرج شوية من الأنترنت. تنقيزة بين الصحاب، ممكن تجرح.",
    naturalExample: "You've been arguing about this for six hours. Touch grass.",
    whenToUse: "Only with friends who share the joke. It can land as rude.",
    formalAlternative: "Perhaps take a break from this.",
    informalAlternative: "Go get some air.",
    register: "slang",
    note: "Slang carries social risk. Understand it everywhere; use it only where you're sure of the relationship.",
    regions: ["usa", "uk", "canada"],
    level: "advanced",
  },
  {
    id: "re-circle-back-biz",
    category: "business",
    phrase: "Let me come back to you on that.",
    meaning: "I don't have the answer now — I'll answer later.",
    darija: "غادي نرجع ليك بجواب من بعد.",
    naturalExample: "Good question. Let me come back to you on that by Thursday.",
    whenToUse: "Client calls and meetings when you're asked something you can't answer.",
    formalAlternative: "I'll revert with a full answer in due course.",
    informalAlternative: "I'll get back to you.",
    register: "formal",
    note: "Adding a date turns a deflection into a commitment. Without it, this phrase can sound like avoidance.",
    regions: ["uk", "usa", "canada", "australia"],
    level: "intermediate",
  },
  {
    id: "re-with-respect",
    category: "business",
    phrase: "With respect, I see it differently.",
    meaning: "I disagree — stated formally and firmly.",
    darija: "مع احترامي، أنا شايف عكس هادشي — اختلاف رسمي وقوي.",
    naturalExample: "With respect, I see it differently: the numbers point the other way.",
    whenToUse: "Formal disagreement in a meeting, especially with someone senior.",
    formalAlternative: "I would respectfully take a different view.",
    informalAlternative: "Hmm, I'm not sure I agree.",
    register: "formal",
    note: "In British usage 'with respect' can carry an edge — it signals a real disagreement, not a soft one. Use it when you mean it.",
    regions: ["uk", "ireland", "australia"],
    level: "advanced",
  },
  {
    id: "re-where-do-we-stand",
    category: "business",
    phrase: "Where do we stand on…?",
    meaning: "What is the current status of…?",
    darija: "فين وصلنا ف…؟",
    naturalExample: "Where do we stand on the supplier contract?",
    whenToUse: "Asking for a status update efficiently in a meeting.",
    formalAlternative: "Could you update me on the current status of…?",
    informalAlternative: "How's the contract going?",
    register: "neutral",
    note: "Status questions are the backbone of meeting English. Two or three reliable forms will carry you through most meetings.",
    regions: ["uk", "usa", "canada", "australia"],
    level: "upper-intermediate",
  },
  {
    id: "re-meet-in-middle",
    category: "business",
    phrase: "Can we meet in the middle?",
    meaning: "Let's compromise between our two positions.",
    darija: "نتلاقاو فالنص — حل وسط.",
    naturalExample: "You're at 40, I'm at 30 — can we meet in the middle at 35?",
    whenToUse: "Negotiation, once both sides have stated a number.",
    formalAlternative: "Might we find a mutually acceptable middle ground?",
    informalAlternative: "Let's split the difference.",
    register: "neutral",
    note: "Naming the compromise number yourself anchors the deal. English negotiation rewards proposing, not just reacting.",
    regions: ["usa", "uk", "canada", "australia", "ireland"],
    level: "upper-intermediate",
  },
  {
    id: "re-not-a-fan",
    category: "business",
    phrase: "I'm not a fan of that approach.",
    meaning: "I don't like it — softened by understatement.",
    darija: "ما عجباتنيش هاد الطريقة — بطريقة مهنية.",
    naturalExample: "I'm not a fan of that approach, mainly because of the timeline.",
    whenToUse: "Professional disagreement where you want to stay collaborative.",
    formalAlternative: "I have some reservations about that approach.",
    informalAlternative: "Yeah, I'm not sold on that.",
    register: "neutral",
    note: "Follow criticism with a reason. Criticism without a reason sounds personal; with a reason it sounds professional.",
    regions: ["usa", "uk", "canada", "australia"],
    level: "upper-intermediate",
  },
];

export const REAL_ENGLISH_BY_ID = new Map(REAL_ENGLISH.map((p) => [p.id, p]));
