import type { VocabularyWord } from "@/types";

/**
 * Vocabulary is never taught as a bare list — every entry carries context,
 * collocations and a real-life example so the learner meets the word the way
 * they will actually meet it.
 */
export const VOCABULARY: VocabularyWord[] = [
  {
    id: "v-catch-up",
    term: "catch up",
    phonetic: "/kætʃ ʌp/",
    partOfSpeech: "phrasal verb",
    definition: "To talk with someone about what has happened since you last met — or to reach the same point as others.",
    example: "Let's catch up next week — it's been ages.",
    realLifeExample: "A colleague passes your desk: 'Hey, we should catch up on the Nakamura account.'",
    collocations: ["catch up with someone", "catch up on work", "a lot to catch up on"],
    similar: ["touch base", "check in", "get up to speed"],
    opposites: ["fall behind", "lose touch"],
    register: "neutral",
    topics: ["workplace", "social", "smalltalk", "meetings"],
    level: "elementary",
  },
  {
    id: "v-heads-up",
    term: "a heads-up",
    phonetic: "/ə ˈhedz ʌp/",
    partOfSpeech: "noun",
    definition: "An advance warning so someone can prepare.",
    example: "Just a heads-up: the client is joining the call at ten.",
    realLifeExample: "Message from your manager at 8am: 'Heads-up — the deadline moved to Thursday.'",
    collocations: ["give someone a heads-up", "just a heads-up", "thanks for the heads-up"],
    similar: ["a warning", "advance notice", "a flag"],
    opposites: ["a surprise", "out of the blue"],
    register: "neutral",
    topics: ["workplace", "email", "meetings", "business"],
    level: "intermediate",
  },
  {
    id: "v-run-by",
    term: "run something by someone",
    phonetic: "/rʌn ˈsʌmθɪŋ baɪ ˈsʌmwʌn/",
    partOfSpeech: "phrasal verb",
    definition: "To tell someone your idea to get their opinion or approval before acting.",
    example: "Can I run something by you before I send it?",
    realLifeExample: "Before replying to a difficult email, you write: 'Mind if I run my draft by you?'",
    collocations: ["run it by legal", "run this by you quickly", "let me run it by my manager"],
    similar: ["check with", "sound out", "get your take on"],
    opposites: ["go ahead without asking", "act unilaterally"],
    register: "neutral",
    topics: ["workplace", "business", "meetings", "email"],
    level: "intermediate",
  },
  {
    id: "v-swamped",
    term: "swamped",
    phonetic: "/swɒmpt/",
    partOfSpeech: "adjective",
    definition: "Having far too much work to handle right now.",
    example: "Sorry for the slow reply — I've been swamped this week.",
    realLifeExample: "Declining a request: 'I'd love to help, but I'm completely swamped until Friday.'",
    collocations: ["absolutely swamped", "swamped with work", "swamped with requests"],
    similar: ["snowed under", "slammed", "flat out"],
    opposites: ["free", "quiet", "have some capacity"],
    register: "casual",
    topics: ["workplace", "email", "smalltalk"],
    level: "intermediate",
  },
  {
    id: "v-touch-base",
    term: "touch base",
    phonetic: "/tʌtʃ beɪs/",
    partOfSpeech: "phrasal verb",
    definition: "To make brief contact with someone to share an update.",
    example: "Let's touch base on Monday and see where we are.",
    realLifeExample: "End of a meeting: 'Great — we'll touch base after you've spoken to the supplier.'",
    collocations: ["touch base with", "touch base quickly", "touch base later this week"],
    similar: ["check in", "circle back", "follow up"],
    opposites: ["go quiet", "drop off the radar"],
    register: "neutral",
    topics: ["workplace", "business", "meetings"],
    level: "intermediate",
  },
  {
    id: "v-get-hang",
    term: "get the hang of it",
    phonetic: "/ɡet ðə hæŋ əv ɪt/",
    partOfSpeech: "idiom",
    definition: "To learn how to do something after some practice.",
    example: "The software is confusing at first, but you get the hang of it.",
    realLifeExample: "Week two in a new job: 'Honestly, I'm just starting to get the hang of it.'",
    collocations: ["get the hang of the system", "you'll get the hang of it", "starting to get the hang of it"],
    similar: ["pick it up", "get used to it", "find your feet"],
    opposites: ["struggle with", "never quite grasp"],
    register: "casual",
    topics: ["workplace", "everyday", "smalltalk", "explaining"],
    level: "elementary",
  },
  {
    id: "v-look-into",
    term: "look into",
    phonetic: "/lʊk ˈɪntuː/",
    partOfSpeech: "phrasal verb",
    definition: "To investigate something to find out what happened or what is possible.",
    example: "I'll look into it and get back to you today.",
    realLifeExample: "A customer reports a missing order; you reply: 'Let me look into this and come back to you within the hour.'",
    collocations: ["look into the issue", "look into options", "I'll look into it"],
    similar: ["investigate", "check", "dig into"],
    opposites: ["ignore", "leave it"],
    register: "neutral",
    topics: ["workplace", "business", "clients", "problems", "admin"],
    level: "elementary",
  },
  {
    id: "v-sort-out",
    term: "sort out",
    phonetic: "/sɔːt aʊt/",
    partOfSpeech: "phrasal verb",
    definition: "To fix a problem or organise something that is messy.",
    example: "Don't worry, we'll sort it out.",
    realLifeExample: "Your booking is wrong at the hotel desk: 'No problem, we'll get that sorted out for you.'",
    collocations: ["sort out the problem", "get it sorted", "sort things out"],
    similar: ["fix", "resolve", "straighten out"],
    opposites: ["make a mess of", "leave unresolved"],
    register: "neutral",
    topics: ["travel", "problems", "everyday", "admin", "hotel"],
    level: "elementary",
  },
  {
    id: "v-put-off",
    term: "put off",
    phonetic: "/pʊt ɒf/",
    partOfSpeech: "phrasal verb",
    definition: "To delay something to a later time — or to make someone lose interest.",
    example: "We had to put the meeting off until Thursday.",
    realLifeExample: "Rescheduling: 'Would it be terrible if we put our call off by a day?'",
    collocations: ["put it off", "put off a decision", "keep putting it off"],
    similar: ["postpone", "push back", "delay"],
    opposites: ["bring forward", "go ahead with"],
    register: "neutral",
    topics: ["workplace", "meetings", "everyday", "admin"],
    level: "elementary",
  },
  {
    id: "v-figure-out",
    term: "figure out",
    phonetic: "/ˈfɪɡər aʊt/",
    partOfSpeech: "phrasal verb",
    definition: "To understand something after thinking about it, or to solve a problem.",
    example: "I can't figure out why the payment failed.",
    realLifeExample: "In front of a ticket machine abroad: 'Give me a second, I'm trying to figure this out.'",
    collocations: ["figure out how to", "figure it out", "still figuring it out"],
    similar: ["work out", "make sense of", "get your head around"],
    opposites: ["be baffled by", "give up on"],
    register: "neutral",
    topics: ["everyday", "problems", "travel", "explaining"],
    level: "elementary",
  },
  {
    id: "v-up-to",
    term: "be up to something",
    phonetic: "/biː ʌp tuː ˈsʌmθɪŋ/",
    partOfSpeech: "idiom",
    definition: "To be doing something — often used to ask what someone is doing generally.",
    example: "What are you up to this weekend?",
    realLifeExample: "Bumping into a friend: 'Hey! What have you been up to lately?'",
    collocations: ["what are you up to", "up to much", "up to anything fun"],
    similar: ["what's going on with you", "what are you doing"],
    opposites: ["nothing much", "not up to a lot"],
    register: "casual",
    topics: ["social", "smalltalk", "friends", "street"],
    level: "beginner",
  },
  {
    id: "v-take-rain-check",
    term: "take a rain check",
    phonetic: "/teɪk ə ˈreɪn tʃek/",
    partOfSpeech: "idiom",
    definition: "To politely decline an invitation now but suggest doing it another time.",
    example: "Can I take a rain check? I'm shattered tonight.",
    realLifeExample: "A colleague invites you for drinks after a long week: 'Can I take a rain check on that?'",
    collocations: ["take a rain check", "rain check on dinner"],
    similar: ["another time", "postpone", "next time for sure"],
    opposites: ["count me in", "I'm there"],
    register: "casual",
    topics: ["social", "friends", "smalltalk"],
    level: "intermediate",
  },
  {
    id: "v-hit-me-up",
    term: "hit me up",
    phonetic: "/hɪt miː ʌp/",
    partOfSpeech: "slang",
    definition: "Contact me — usually by message.",
    example: "Hit me up when you land.",
    realLifeExample: "Saying goodbye to a new friend: 'Hit me up if you're ever in Lisbon.'",
    collocations: ["hit me up later", "hit me up on WhatsApp"],
    similar: ["message me", "give me a shout", "text me"],
    opposites: ["don't contact me"],
    register: "slang",
    topics: ["social", "internet", "street", "friends"],
    level: "intermediate",
  },
  {
    id: "v-no-worries",
    term: "no worries",
    phonetic: "/nəʊ ˈwʌriz/",
    partOfSpeech: "expression",
    definition: "It's fine / don't apologise / you're welcome. Extremely common in Australia and the UK.",
    example: "— Sorry I'm late! — No worries.",
    realLifeExample: "You bump into someone on the train and apologise; they answer: 'No worries, mate.'",
    collocations: ["no worries at all", "yeah, no worries"],
    similar: ["no problem", "you're good", "all good"],
    opposites: ["that's not okay"],
    register: "casual",
    topics: ["social", "travel", "everyday", "street"],
    level: "beginner",
  },
  {
    id: "v-look-forward",
    term: "look forward to",
    phonetic: "/lʊk ˈfɔːwəd tuː/",
    partOfSpeech: "phrasal verb",
    definition: "To feel pleased about something that is going to happen. Followed by a noun or -ing.",
    example: "I look forward to hearing from you.",
    realLifeExample: "Closing a professional email after an interview: 'I look forward to hearing from you.'",
    collocations: ["look forward to hearing from you", "really looking forward to it"],
    similar: ["can't wait for", "be excited about"],
    opposites: ["dread", "be anxious about"],
    register: "formal",
    topics: ["email", "workplace", "business", "admin"],
    level: "elementary",
  },
  {
    id: "v-bear-with",
    term: "bear with me",
    phonetic: "/beə wɪð miː/",
    partOfSpeech: "expression",
    definition: "Please be patient for a short moment.",
    example: "Bear with me — I'm just pulling up the file.",
    realLifeExample: "On a support call: 'Bear with me one moment while I check your account.'",
    collocations: ["bear with me a second", "thanks for bearing with us"],
    similar: ["give me a moment", "hang on", "one sec"],
    opposites: ["hurry up"],
    register: "neutral",
    topics: ["workplace", "phone", "clients", "admin"],
    level: "intermediate",
  },
  {
    id: "v-circle-back",
    term: "circle back",
    phonetic: "/ˈsɜːkl bæk/",
    partOfSpeech: "phrasal verb",
    definition: "To return to a topic later — very common in meetings, sometimes seen as corporate jargon.",
    example: "Let's circle back to the budget at the end.",
    realLifeExample: "A discussion goes off track: 'Good point — can we circle back to that after the demo?'",
    collocations: ["circle back on", "circle back to this", "let's circle back later"],
    similar: ["come back to", "revisit", "return to"],
    opposites: ["drop the subject", "close the topic"],
    register: "neutral",
    topics: ["meetings", "business", "workplace"],
    level: "upper-intermediate",
  },
  {
    id: "v-ballpark",
    term: "a ballpark figure",
    phonetic: "/ə ˈbɔːlpɑːk ˈfɪɡə/",
    partOfSpeech: "noun phrase",
    definition: "An approximate number, close enough to be useful.",
    example: "Can you give me a ballpark figure for the cost?",
    realLifeExample: "Client on a call: 'I don't need the exact quote — just a ballpark.'",
    collocations: ["ballpark figure", "in the right ballpark", "ballpark estimate"],
    similar: ["a rough estimate", "an approximate number"],
    opposites: ["an exact quote", "a precise figure"],
    register: "neutral",
    topics: ["business", "negotiation", "clients", "meetings"],
    level: "upper-intermediate",
  },
  {
    id: "v-get-back-to",
    term: "get back to someone",
    phonetic: "/ɡet bæk tuː ˈsʌmwʌn/",
    partOfSpeech: "phrasal verb",
    definition: "To reply to someone later with an answer.",
    example: "I'll get back to you by the end of the day.",
    realLifeExample: "You don't have an answer yet: 'Let me check with the team and get back to you.'",
    collocations: ["get back to you shortly", "get back to me on that"],
    similar: ["follow up with", "come back to you", "revert (very formal)"],
    opposites: ["leave someone hanging", "ghost someone"],
    register: "neutral",
    topics: ["workplace", "email", "clients", "business", "phone"],
    level: "elementary",
  },
  {
    id: "v-drop-by",
    term: "drop by",
    phonetic: "/drɒp baɪ/",
    partOfSpeech: "phrasal verb",
    definition: "To visit somewhere briefly, usually without a formal plan.",
    example: "I might drop by after work.",
    realLifeExample: "Neighbour at the door: 'I just dropped by to say hi.'",
    collocations: ["drop by the office", "drop by later", "feel free to drop by"],
    similar: ["stop by", "swing by", "pop in"],
    opposites: ["make an appointment"],
    register: "casual",
    topics: ["social", "everyday", "friends", "street"],
    level: "elementary",
  },
  {
    id: "v-make-it",
    term: "make it",
    phonetic: "/meɪk ɪt/",
    partOfSpeech: "phrasal verb",
    definition: "To manage to attend or arrive — or to succeed.",
    example: "Sorry, I can't make it tomorrow.",
    realLifeExample: "Declining a meeting invite: 'I can't make it at 3, but I'm free at 4.'",
    collocations: ["can you make it", "can't make it", "made it just in time"],
    similar: ["be able to come", "attend", "get there"],
    opposites: ["miss it", "be a no-show"],
    register: "neutral",
    topics: ["social", "workplace", "meetings", "everyday"],
    level: "beginner",
  },
  {
    id: "v-run-late",
    term: "run late",
    phonetic: "/rʌn leɪt/",
    partOfSpeech: "phrasal verb",
    definition: "To be behind schedule.",
    example: "I'm running about ten minutes late.",
    realLifeExample: "Text before a meeting: 'Running 10 late, sorry — start without me.'",
    collocations: ["running late", "running a bit late", "the train is running late"],
    similar: ["be delayed", "be behind schedule"],
    opposites: ["be early", "be on time"],
    register: "neutral",
    topics: ["everyday", "travel", "workplace", "phone"],
    level: "beginner",
  },
  {
    id: "v-heads-or-tails-hold-on",
    term: "hold on",
    phonetic: "/həʊld ɒn/",
    partOfSpeech: "phrasal verb",
    definition: "Wait a moment — also used to interrupt politely when something doesn't add up.",
    example: "Hold on, I thought the deadline was Friday?",
    realLifeExample: "On the phone: 'Hold on a sec, I'll put you through.'",
    collocations: ["hold on a second", "hold on a minute", "hold on, let me check"],
    similar: ["hang on", "wait a second", "just a moment"],
    opposites: ["go ahead", "carry on"],
    register: "casual",
    topics: ["phone", "everyday", "meetings", "problems"],
    level: "beginner",
  },
  {
    id: "v-check-in",
    term: "check in",
    phonetic: "/tʃek ɪn/",
    partOfSpeech: "phrasal verb",
    definition: "To register at a hotel or airport — or to contact someone to see how things are going.",
    example: "What time can I check in?",
    realLifeExample: "At the airport: 'Has this flight started checking in yet?'",
    collocations: ["check in online", "check in at the desk", "check in with someone"],
    similar: ["register", "touch base"],
    opposites: ["check out"],
    register: "neutral",
    topics: ["travel", "hotel", "workplace", "admin"],
    level: "beginner",
  },
  {
    id: "v-fill-out",
    term: "fill out (a form)",
    phonetic: "/fɪl aʊt/",
    partOfSpeech: "phrasal verb",
    definition: "To write the required information on a form. British English also says 'fill in'.",
    example: "You'll need to fill out this form before the appointment.",
    realLifeExample: "At a clinic reception: 'Fill this out and bring it back to me when you're done.'",
    collocations: ["fill out an application", "fill out the paperwork", "fill in the blanks"],
    similar: ["complete", "fill in"],
    opposites: ["leave blank"],
    register: "neutral",
    topics: ["admin", "forms", "health", "housing"],
    level: "beginner",
  },
  {
    id: "v-set-up",
    term: "set up",
    phonetic: "/set ʌp/",
    partOfSpeech: "phrasal verb",
    definition: "To arrange or create something: an account, an appointment, a system.",
    example: "I need to set up a bank account.",
    realLifeExample: "New in a country: 'How long does it take to set up internet at home?'",
    collocations: ["set up an account", "set up a meeting", "get set up"],
    similar: ["arrange", "open", "create"],
    opposites: ["close", "cancel", "shut down"],
    register: "neutral",
    topics: ["admin", "housing", "workplace", "forms"],
    level: "beginner",
  },
  {
    id: "v-turn-down",
    term: "turn down",
    phonetic: "/tɜːn daʊn/",
    partOfSpeech: "phrasal verb",
    definition: "To refuse an offer — or to lower the volume.",
    example: "They turned down our first offer.",
    realLifeExample: "After a negotiation: 'They turned it down, but they left the door open.'",
    collocations: ["turn down an offer", "turn down a job", "turn it down a bit"],
    similar: ["reject", "decline", "pass on"],
    opposites: ["accept", "take up"],
    register: "neutral",
    topics: ["business", "negotiation", "workplace"],
    level: "intermediate",
  },
  {
    id: "v-push-back",
    term: "push back",
    phonetic: "/pʊʃ bæk/",
    partOfSpeech: "phrasal verb / noun",
    definition: "To resist or disagree with a plan — or to move a date later.",
    example: "The team pushed back on the timeline.",
    realLifeExample: "Reporting to your boss: 'We got some pushback from finance, so I've pushed the launch back a week.'",
    collocations: ["push back on", "get pushback", "push the date back"],
    similar: ["resist", "object", "postpone"],
    opposites: ["agree", "go along with", "bring forward"],
    register: "neutral",
    topics: ["business", "workplace", "meetings", "negotiation"],
    level: "upper-intermediate",
  },
  {
    id: "v-take-on",
    term: "take on",
    phonetic: "/teɪk ɒn/",
    partOfSpeech: "phrasal verb",
    definition: "To accept work or responsibility — or to hire someone.",
    example: "I can't take on any more projects this month.",
    realLifeExample: "Protecting your workload: 'I'd rather not take that on until the audit is finished.'",
    collocations: ["take on a project", "take on more work", "take on staff"],
    similar: ["accept", "assume responsibility for"],
    opposites: ["turn down", "hand over", "delegate"],
    register: "neutral",
    topics: ["workplace", "business", "meetings"],
    level: "intermediate",
  },
  {
    id: "v-wrap-up",
    term: "wrap up",
    phonetic: "/ræp ʌp/",
    partOfSpeech: "phrasal verb",
    definition: "To finish something — a meeting, a task, a day.",
    example: "Let's wrap up — we're at time.",
    realLifeExample: "Chairing a call: 'I'd like to wrap up with three action points.'",
    collocations: ["wrap up the meeting", "wrap things up", "wrap up for the day"],
    similar: ["finish", "conclude", "close out"],
    opposites: ["kick off", "get started"],
    register: "neutral",
    topics: ["meetings", "workplace", "business", "presentation"],
    level: "intermediate",
  },
  {
    id: "v-kick-off",
    term: "kick off",
    phonetic: "/kɪk ɒf/",
    partOfSpeech: "phrasal verb",
    definition: "To start something, especially an event or project.",
    example: "Let's kick off with a quick round of intros.",
    realLifeExample: "Opening a workshop: 'Before we kick off, has everyone got the deck?'",
    collocations: ["kick off a meeting", "kick off the project", "kick-off call"],
    similar: ["begin", "start", "get underway"],
    opposites: ["wrap up", "finish"],
    register: "neutral",
    topics: ["meetings", "business", "presentation", "workplace"],
    level: "intermediate",
  },
  {
    id: "v-follow-up",
    term: "follow up",
    phonetic: "/ˈfɒləʊ ʌp/",
    partOfSpeech: "phrasal verb / noun",
    definition: "To contact someone again about something discussed earlier.",
    example: "I'm following up on my email from Monday.",
    realLifeExample: "Chasing a silent client politely: 'Just following up on the proposal — any thoughts?'",
    collocations: ["follow up on", "a quick follow-up", "follow up with the client"],
    similar: ["chase", "check in", "circle back"],
    opposites: ["let it drop"],
    register: "neutral",
    topics: ["email", "business", "clients", "workplace"],
    level: "intermediate",
  },
  {
    id: "v-come-across",
    term: "come across",
    phonetic: "/kʌm əˈkrɒs/",
    partOfSpeech: "phrasal verb",
    definition: "To give a particular impression — or to find something by chance.",
    example: "I didn't want to come across as rude.",
    realLifeExample: "After a tense email: 'Reading it again, I think it came across harsher than I meant.'",
    collocations: ["come across as", "come across well", "came across an article"],
    similar: ["seem", "give the impression", "stumble upon"],
    opposites: ["be misread", "look for deliberately"],
    register: "neutral",
    topics: ["social", "workplace", "opinion", "email"],
    level: "upper-intermediate",
  },
  {
    id: "v-get-point-across",
    term: "get your point across",
    phonetic: "/ɡet jɔː pɔɪnt əˈkrɒs/",
    partOfSpeech: "idiom",
    definition: "To make people understand what you mean.",
    example: "My grammar isn't perfect, but I get my point across.",
    realLifeExample: "Self-assessment after a meeting: 'I got my point across, even if I hesitated.'",
    collocations: ["get the point across", "struggle to get my point across"],
    similar: ["make yourself understood", "convey your meaning"],
    opposites: ["be misunderstood", "lose your audience"],
    register: "neutral",
    topics: ["opinion", "explaining", "presentation", "meetings"],
    level: "intermediate",
  },
  {
    id: "v-in-a-nutshell",
    term: "in a nutshell",
    phonetic: "/ɪn ə ˈnʌtʃel/",
    partOfSpeech: "idiom",
    definition: "In summary, in very few words.",
    example: "In a nutshell, we need two more weeks.",
    realLifeExample: "Ending a long explanation to a busy manager: 'In a nutshell: it works, but it's slow.'",
    collocations: ["in a nutshell", "that's it in a nutshell"],
    similar: ["to sum up", "long story short", "basically"],
    opposites: ["in detail", "at length"],
    register: "neutral",
    topics: ["presentation", "explaining", "meetings", "academic"],
    level: "intermediate",
  },
  {
    id: "v-long-story-short",
    term: "long story short",
    phonetic: "/lɒŋ ˈstɔːri ʃɔːt/",
    partOfSpeech: "idiom",
    definition: "Skipping the details to get to the result of a story.",
    example: "Long story short, we missed the flight.",
    realLifeExample: "Telling a friend about your weekend: 'Long story short — we ended up walking home.'",
    collocations: ["long story short", "to cut a long story short (UK)"],
    similar: ["anyway", "bottom line", "to sum up"],
    opposites: ["let me explain in detail"],
    register: "casual",
    topics: ["stories", "social", "smalltalk", "friends"],
    level: "intermediate",
  },
  {
    id: "v-bottom-line",
    term: "the bottom line",
    phonetic: "/ðə ˈbɒtəm laɪn/",
    partOfSpeech: "noun phrase",
    definition: "The most important fact or the final result — also, literally, profit.",
    example: "The bottom line is we can't afford it this quarter.",
    realLifeExample: "Cutting through debate: 'Bottom line — can we ship by March or not?'",
    collocations: ["the bottom line is", "affect the bottom line", "bottom-line impact"],
    similar: ["the key point", "what it comes down to"],
    opposites: ["the details", "side issues"],
    register: "neutral",
    topics: ["business", "negotiation", "meetings", "presentation"],
    level: "upper-intermediate",
  },
  {
    id: "v-on-the-same-page",
    term: "on the same page",
    phonetic: "/ɒn ðə seɪm peɪdʒ/",
    partOfSpeech: "idiom",
    definition: "In agreement, with the same understanding of a situation.",
    example: "I just want to make sure we're on the same page.",
    realLifeExample: "Before a client call: 'Quick sync so we're on the same page about pricing.'",
    collocations: ["get on the same page", "we're on the same page"],
    similar: ["in agreement", "aligned", "of one mind"],
    opposites: ["at cross purposes", "misaligned"],
    register: "neutral",
    topics: ["meetings", "business", "workplace", "clients"],
    level: "intermediate",
  },
  {
    id: "v-hang-of-second-thoughts",
    term: "have second thoughts",
    phonetic: "/hæv ˈsekənd θɔːts/",
    partOfSpeech: "idiom",
    definition: "To start to doubt a decision you already made.",
    example: "I'm having second thoughts about moving.",
    realLifeExample: "Talking to a friend about a job offer: 'I said yes, but I'm having second thoughts.'",
    collocations: ["having second thoughts about", "no second thoughts"],
    similar: ["reconsider", "doubt", "get cold feet"],
    opposites: ["be certain", "have no doubts"],
    register: "neutral",
    topics: ["social", "opinion", "everyday", "friends"],
    level: "intermediate",
  },
  {
    id: "v-look-around",
    term: "have a look around",
    phonetic: "/hæv ə lʊk əˈraʊnd/",
    partOfSpeech: "expression",
    definition: "To browse or explore a place without a specific goal.",
    example: "I'm just having a look around, thanks.",
    realLifeExample: "A shop assistant asks if you need help: 'I'm just having a look around, thanks.'",
    collocations: ["have a look around", "look around the neighbourhood"],
    similar: ["browse", "wander around", "explore"],
    opposites: ["know exactly what you want"],
    register: "casual",
    topics: ["travel", "everyday", "street", "shopping"],
    level: "beginner",
  },
  {
    id: "v-whereabouts",
    term: "whereabouts",
    phonetic: "/ˈweərəbaʊts/",
    partOfSpeech: "adverb / noun",
    definition: "Where exactly — a friendlier, less direct way of asking for a location.",
    example: "Whereabouts are you staying?",
    realLifeExample: "Small talk with a taxi driver: 'Whereabouts in the city are you from?'",
    collocations: ["whereabouts exactly", "whereabouts are you"],
    similar: ["where exactly", "in which part"],
    opposites: [],
    register: "casual",
    topics: ["travel", "smalltalk", "social", "directions"],
    level: "intermediate",
  },
  {
    id: "v-put-through",
    term: "put someone through",
    phonetic: "/pʊt ˈsʌmwʌn θruː/",
    partOfSpeech: "phrasal verb",
    definition: "To connect a caller to another person on the phone.",
    example: "Can you put me through to the billing department?",
    realLifeExample: "Calling a clinic: 'I'll put you through to reception now.'",
    collocations: ["put you through", "put me through to"],
    similar: ["transfer a call", "connect"],
    opposites: ["hang up", "cut off"],
    register: "formal",
    topics: ["phone", "admin", "clients", "health"],
    level: "intermediate",
  },
  {
    id: "v-hold-the-line",
    term: "hold the line",
    phonetic: "/həʊld ðə laɪn/",
    partOfSpeech: "expression",
    definition: "Stay on the phone and wait.",
    example: "Please hold the line while I check.",
    realLifeExample: "Automated message: 'Please hold the line — your call is important to us.'",
    collocations: ["hold the line please", "holding the line"],
    similar: ["stay on the line", "please hold", "bear with me"],
    opposites: ["hang up"],
    register: "formal",
    topics: ["phone", "admin", "clients"],
    level: "intermediate",
  },
  {
    id: "v-run-through",
    term: "run through",
    phonetic: "/rʌn θruː/",
    partOfSpeech: "phrasal verb",
    definition: "To quickly review or rehearse something from start to finish.",
    example: "Let's run through the slides one more time.",
    realLifeExample: "Before a presentation: 'Can we run through the intro once so it lands?'",
    collocations: ["run through the agenda", "a quick run-through", "run through it again"],
    similar: ["go over", "rehearse", "walk through"],
    opposites: ["skip", "improvise"],
    register: "neutral",
    topics: ["presentation", "meetings", "academic", "business"],
    level: "intermediate",
  },
  {
    id: "v-take-away",
    term: "the main takeaway",
    phonetic: "/ðə meɪn ˈteɪkəweɪ/",
    partOfSpeech: "noun phrase",
    definition: "The key message someone should remember.",
    example: "The main takeaway is that users don't read instructions.",
    realLifeExample: "Ending a lecture: 'If you remember one thing, let it be this takeaway.'",
    collocations: ["key takeaway", "main takeaway", "takeaways from the meeting"],
    similar: ["key point", "the lesson", "the upshot"],
    opposites: ["a side note", "a detail"],
    register: "neutral",
    topics: ["academic", "presentation", "meetings", "lecture"],
    level: "upper-intermediate",
  },
  {
    id: "v-wrap-head-around",
    term: "get your head around something",
    phonetic: "/ɡet jɔː hed əˈraʊnd/",
    partOfSpeech: "idiom",
    definition: "To finally understand something difficult or surprising.",
    example: "I still can't get my head around the new system.",
    realLifeExample: "A student after a hard lecture: 'Give me a day to get my head around it.'",
    collocations: ["can't get my head around it", "getting my head around the idea"],
    similar: ["make sense of", "grasp", "wrap your head around (US)"],
    opposites: ["find obvious", "grasp instantly"],
    register: "casual",
    topics: ["academic", "explaining", "everyday", "lecture"],
    level: "upper-intermediate",
  },
  {
    id: "v-fair-enough",
    term: "fair enough",
    phonetic: "/feər ɪˈnʌf/",
    partOfSpeech: "expression",
    definition: "I accept your reason — even if I don't fully agree.",
    example: "— I'd rather not decide today. — Fair enough.",
    realLifeExample: "A friend cancels plans and explains why: 'Fair enough, let's do next week.'",
    collocations: ["fair enough", "that's fair enough"],
    similar: ["that's reasonable", "I get it", "understood"],
    opposites: ["that's not good enough"],
    register: "casual",
    topics: ["social", "opinion", "smalltalk", "reacting"],
    level: "intermediate",
  },
  {
    id: "v-i-see-your-point",
    term: "I see your point, but…",
    phonetic: "/aɪ siː jɔː pɔɪnt/",
    partOfSpeech: "expression",
    definition: "A polite way to disagree: acknowledge first, then object.",
    example: "I see your point, but the data says otherwise.",
    realLifeExample: "In a heated meeting: 'I see your point — my concern is the cost.'",
    collocations: ["I see your point", "I take your point", "point taken"],
    similar: ["I hear you, but", "that's a fair point, however"],
    opposites: ["you're wrong", "that makes no sense"],
    register: "formal",
    topics: ["meetings", "opinion", "business", "discussion", "negotiation"],
    level: "upper-intermediate",
  },
  {
    id: "v-off-the-top-of-my-head",
    term: "off the top of my head",
    phonetic: "/ɒf ðə tɒp əv maɪ hed/",
    partOfSpeech: "idiom",
    definition: "From memory, without checking — so the answer might not be exact.",
    example: "Off the top of my head, about forty users.",
    realLifeExample: "Asked for a number you don't have: 'Off the top of my head, around 15% — let me confirm.'",
    collocations: ["off the top of my head", "not off the top of my head"],
    similar: ["from memory", "roughly", "a ballpark"],
    opposites: ["after checking", "precisely"],
    register: "casual",
    topics: ["meetings", "workplace", "smalltalk", "business"],
    level: "upper-intermediate",
  },
  {
    id: "v-keep-me-posted",
    term: "keep me posted",
    phonetic: "/kiːp miː ˈpəʊstɪd/",
    partOfSpeech: "expression",
    definition: "Continue to tell me what happens.",
    example: "Sounds good — keep me posted.",
    realLifeExample: "End of a chat about a job application: 'Good luck! Keep me posted.'",
    collocations: ["keep me posted on", "keep me in the loop"],
    similar: ["keep me in the loop", "let me know how it goes"],
    opposites: ["leave me out of it"],
    register: "neutral",
    topics: ["workplace", "social", "email", "friends"],
    level: "intermediate",
  },
  {
    id: "v-cant-complain",
    term: "can't complain",
    phonetic: "/kɑːnt kəmˈpleɪn/",
    partOfSpeech: "expression",
    definition: "A modest, friendly way to say things are going fine.",
    example: "— How's it going? — Can't complain.",
    realLifeExample: "Colleague in the lift: 'How've you been?' — 'Yeah, can't complain.'",
    collocations: ["can't complain", "can't complain really"],
    similar: ["not bad", "pretty good", "all good"],
    opposites: ["it's been rough"],
    register: "casual",
    topics: ["smalltalk", "social", "street", "reacting"],
    level: "elementary",
  },
  {
    id: "v-spot-on",
    term: "spot on",
    phonetic: "/spɒt ɒn/",
    partOfSpeech: "adjective (esp. British)",
    definition: "Exactly right.",
    example: "Your estimate was spot on.",
    realLifeExample: "A colleague predicts a client's objection correctly: 'That was spot on.'",
    collocations: ["absolutely spot on", "spot-on analysis"],
    similar: ["exactly right", "bang on (UK)", "nailed it"],
    opposites: ["way off", "miles off"],
    register: "casual",
    topics: ["workplace", "reacting", "opinion", "british"],
    level: "intermediate",
  },
  {
    id: "v-hang-in-there",
    term: "hang in there",
    phonetic: "/hæŋ ɪn ðeə/",
    partOfSpeech: "expression",
    definition: "Keep going through a difficult period.",
    example: "Hang in there — it gets easier.",
    realLifeExample: "Message to a friend in a hard first month abroad: 'Hang in there, month three is different.'",
    collocations: ["hang in there", "just hang in there"],
    similar: ["stick with it", "keep at it", "don't give up"],
    opposites: ["give up", "throw in the towel"],
    register: "casual",
    topics: ["social", "friends", "reacting", "everyday"],
    level: "elementary",
  },
  {
    id: "v-cut-corners",
    term: "cut corners",
    phonetic: "/kʌt ˈkɔːnəz/",
    partOfSpeech: "idiom",
    definition: "To do something cheaply or quickly by skipping important steps.",
    example: "We can't cut corners on safety.",
    realLifeExample: "Reviewing a rushed plan: 'It works, but we've cut corners on testing.'",
    collocations: ["cut corners on", "no cutting corners"],
    similar: ["take shortcuts", "do a rush job"],
    opposites: ["do it properly", "be thorough"],
    register: "neutral",
    topics: ["business", "workplace", "opinion", "negotiation"],
    level: "upper-intermediate",
  },
  {
    id: "v-up-in-the-air",
    term: "up in the air",
    phonetic: "/ʌp ɪn ði eə/",
    partOfSpeech: "idiom",
    definition: "Not decided yet, uncertain.",
    example: "The dates are still up in the air.",
    realLifeExample: "Asked about your holiday plans: 'Everything's a bit up in the air right now.'",
    collocations: ["still up in the air", "left up in the air"],
    similar: ["undecided", "unclear", "TBC"],
    opposites: ["settled", "confirmed", "locked in"],
    register: "casual",
    topics: ["workplace", "social", "travel", "smalltalk"],
    level: "upper-intermediate",
  },
  {
    id: "v-a-quick-one",
    term: "a quick one",
    phonetic: "/ə kwɪk wʌn/",
    partOfSpeech: "noun phrase",
    definition: "A short question, meeting or drink.",
    example: "Quick one — do you have the file?",
    realLifeExample: "Chat message: 'Quick one: is the invoice already paid?'",
    collocations: ["quick one for you", "a quick one after work"],
    similar: ["a short question", "one small thing"],
    opposites: ["a long discussion"],
    register: "casual",
    topics: ["workplace", "smalltalk", "internet", "email"],
    level: "intermediate",
  },
  {
    id: "v-i-am-down",
    term: "I'm down",
    phonetic: "/aɪm daʊn/",
    partOfSpeech: "slang (esp. American)",
    definition: "I'm willing / count me in. Note: 'I'm down' ≠ 'I'm feeling down'.",
    example: "— Pizza tonight? — I'm down.",
    realLifeExample: "Group chat plans: 'I'm down for Saturday, not Friday.'",
    collocations: ["I'm down for that", "you down?"],
    similar: ["I'm in", "count me in", "sounds good"],
    opposites: ["I'll pass", "not for me"],
    register: "slang",
    topics: ["social", "friends", "american", "internet"],
    level: "intermediate",
  },
  {
    id: "v-lowkey",
    term: "lowkey",
    phonetic: "/ˈləʊkiː/",
    partOfSpeech: "slang adverb",
    definition: "Slightly / secretly — used to soften an admission online and in casual speech.",
    example: "I'm lowkey nervous about tomorrow.",
    realLifeExample: "Text to a friend: 'lowkey hoping the meeting gets cancelled.'",
    collocations: ["lowkey excited", "lowkey stressed"],
    similar: ["kind of", "secretly", "a bit"],
    opposites: ["highkey", "openly"],
    register: "slang",
    topics: ["internet", "social", "media", "friends"],
    level: "upper-intermediate",
  },
  {
    id: "v-no-cap",
    term: "no cap",
    phonetic: "/nəʊ kæp/",
    partOfSpeech: "slang",
    definition: "No lie / seriously. Young, informal, mostly American and online.",
    example: "That was the best meal I've had all year, no cap.",
    realLifeExample: "A comment under a video: 'no cap, this changed how I study.'",
    collocations: ["no cap", "that's cap (= that's a lie)"],
    similar: ["for real", "I'm serious", "honestly"],
    opposites: ["just kidding"],
    register: "slang",
    topics: ["internet", "media", "american", "street"],
    level: "advanced",
  },
  {
    id: "v-knackered",
    term: "knackered",
    phonetic: "/ˈnækəd/",
    partOfSpeech: "adjective (British)",
    definition: "Extremely tired. Very common in the UK and Ireland, informal.",
    example: "I'm absolutely knackered after that shift.",
    realLifeExample: "Friday evening with UK colleagues: 'I'm knackered — straight home for me.'",
    collocations: ["absolutely knackered", "knackered after work"],
    similar: ["shattered (UK)", "exhausted", "wiped out (US)"],
    opposites: ["full of energy", "fresh"],
    register: "slang",
    topics: ["british", "social", "street", "everyday"],
    level: "upper-intermediate",
  },
  {
    id: "v-arvo",
    term: "arvo",
    phonetic: "/ˈɑːvəʊ/",
    partOfSpeech: "noun (Australian)",
    definition: "Afternoon. Australian abbreviation, casual only.",
    example: "See you this arvo.",
    realLifeExample: "Australian colleague: 'Let's sort it out this arvo.'",
    collocations: ["this arvo", "tomorrow arvo"],
    similar: ["afternoon"],
    opposites: [],
    register: "slang",
    topics: ["australia", "social", "street", "travel"],
    level: "advanced",
  },
  {
    id: "v-grand",
    term: "grand (Irish usage)",
    phonetic: "/ɡrænd/",
    partOfSpeech: "adjective (Irish)",
    definition: "Fine, okay, no problem — in Ireland it means 'fine', not 'magnificent'.",
    example: "— Sorry about that! — You're grand.",
    realLifeExample: "In a Dublin café, you apologise for blocking the way: 'You're grand.'",
    collocations: ["that's grand", "you're grand", "grand so"],
    similar: ["fine", "no worries", "all good"],
    opposites: ["not okay"],
    register: "casual",
    topics: ["ireland", "travel", "social", "street"],
    level: "advanced",
  },
];

export const VOCABULARY_BY_ID = new Map(VOCABULARY.map((w) => [w.id, w]));
